/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Control.ControlDeNavegacion;
import Control.IControl;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Ramon Valencia
 */
public class InicioSesion extends VentanaBase {
    private JPanel panelCentral;
    private ControlDeNavegacion navegacion;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(IControl control) {
        super(control, "Inicio de Sesion");
        navegacion = ControlDeNavegacion.getInstance();
        generarInicioSesion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMesero = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));

        botonMesero.setText("Mesero");
        botonMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMeseroActionPerformed(evt);
            }
        });

        botonSalir.setText("jButton3");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });

        botonAdministrador.setText("Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(botonAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(96, 96, 96)
                .addComponent(botonMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMeseroActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
  
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirMouseClicked
    private void botonAdministradorMouseClicked(java.awt.event.MouseEvent evt) {
        navegacion.registrarVentana("Menu Administrador", new MenuAdministrador(control));
        navegacion.abrirVentana("Menu Administrador");
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonMesero;
    private javax.swing.JButton botonSalir;
    // End of variables declaration//GEN-END:variables
    
    

    
    private void generarInicioSesion() {
        
        botonAdministrador = new JButton("ADMINISTRADOR");
        botonMesero = new JButton("MESERO");
        panelCentral = new JPanel();
        botonSalir = new JButton("SALIR");
        generarPanelCentral(panelCentral, botonAdministrador, botonMesero);
        generarBotonSalir(botonSalir);
    }
    
    private void generarPanelCentral(JPanel panelCentral, JButton btnAdmin, JButton btnMesero) {
        Dimension tamañoPanel = new Dimension(400, 300);
        panelCentral.setPreferredSize(tamañoPanel);
        panelCentral.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));
        //panelCentral.setLayout(new BoxLayout(panelCentral, BoxLayout.X_AXIS));
        configurarBtnAdmin(btnAdmin);
        btnMesero.setPreferredSize(new Dimension(400, 100));
        btnMesero.revalidate();
        btnMesero.repaint();
        
        panelCentral.add(btnAdmin);
        //panelCentral.add
        panelCentral.add(btnMesero);
        
        this.add(panelCentral, BorderLayout.CENTER);
    }
    
    private void configurarBtnAdmin(JButton btnAdmin) {
        btnAdmin.setPreferredSize(new Dimension(400, 100));
        btnAdmin.revalidate();
        btnAdmin.repaint();
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAdministradorMouseClicked(evt);
            }
        });
    }
    
    private void generarBotonSalir(JButton boton) {
        JPanel panelSur = (JPanel) this.getContentPane().getComponent(0);
        boton.setPreferredSize(new Dimension(125, 70));
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        boton.revalidate();
        boton.repaint();
        panelSur.setLayout(new FlowLayout(FlowLayout.LEFT));
        panelSur.add(boton);
        panelSur.revalidate();
        panelSur.repaint();
    }
}
