/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Control.ControlDeNavegacion;
import Control.IControl;
import Control.TipoVentana;
import Control.VentanaFactory;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Ramon Valencia
 */
public class MenuAdministrador extends VentanaBase {
    private IControl navegacion;
    
    public MenuAdministrador(IControl control) {
        super(control, "Menu de Administrador");
        navegacion = ControlDeNavegacion.getInstance();
        generarMenuAdministrador();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegreso = new javax.swing.JButton();
        btnComandas = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegreso.setText("jButton1");

        btnComandas.setText("jButton1");

        btnProductos.setText("jButton2");

        btnIngredientes.setText("jButton3");

        btnClientes.setText("jButton4");

        btnReportes.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnRegreso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnComandas)
                        .addGap(35, 35, 35)
                        .addComponent(btnProductos)
                        .addGap(39, 39, 39)
                        .addComponent(btnIngredientes)
                        .addGap(43, 43, 43)
                        .addComponent(btnClientes)
                        .addGap(38, 38, 38)
                        .addComponent(btnReportes)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComandas)
                    .addComponent(btnProductos)
                    .addComponent(btnIngredientes)
                    .addComponent(btnClientes)
                    .addComponent(btnReportes))
                .addGap(298, 298, 298)
                .addComponent(btnRegreso)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que detecta cuando el boton de regreso es presionado
     * @param evt 
     */
    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        navegacion.registrarVentana("Inicio Sesion", new InicioSesion(control));
        navegacion.abrirVentana("Inicio Sesion");
        navegacion.cerrarVentana("Menu Administrador");
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnComandas;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JButton btnReportes;
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo que se encarga de la generacion del menu de administrador
     */
    private void generarMenuAdministrador(){
        JPanel panelCentral = new JPanel();
        btnRegreso = new JButton("LOG OUT");
        btnClientes = new JButton("Modulo de Clientes Frecuentes");
        configuracionBotonModulo(btnClientes, "Menu de Clientes Frecuentes", TipoVentana.CLIENTES);
        btnComandas = new JButton("Modulo de Comandas");
        configuracionBotonModulo(btnComandas, "Menu Comandas", TipoVentana.COMANDAS);
        btnIngredientes = new JButton("Modulo de Ingredientes");
        configuracionBotonModulo(btnIngredientes, "Menu de Ingredientes", TipoVentana.INGREDIENTES);
        btnProductos = new JButton("Modulo de Productos");
        configuracionBotonModulo(btnProductos, "Menu de Productos", TipoVentana.PRODUCTOS);
        btnReportes = new JButton("Modulo de Reportes");
        generarPanelCentral(panelCentral);
        generarBotonRegreso(btnRegreso);
    }
    
    /**
     * Metodo que se encaraga de generar el Panel Central donde iran todos los botones
     * @param panelCentral 
     */
    private void generarPanelCentral(JPanel panelCentral){
        panelCentral.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10); 
        
        gbc.gridy = 0; 
        gbc.gridx = 0;
        panelCentral.add(btnComandas, gbc);

        gbc.gridx = 1;
        panelCentral.add(btnProductos, gbc);

        gbc.gridx = 2;
        panelCentral.add(btnIngredientes, gbc);

        gbc.gridy = 1; 
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        panelCentral.add(btnReportes, gbc);
        
        gbc.gridx = 1;
        panelCentral.add(btnClientes, gbc);
        
        panelCentral.revalidate();
        panelCentral.repaint();
        add(panelCentral, BorderLayout.CENTER);
    }
    /**
     * Metodo necesario para la generacion del boton de regreso
     * @param boton 
     */
    private void generarBotonRegreso(JButton boton) {
        JPanel panelSur = (JPanel) this.getContentPane().getComponent(0);
        boton.setPreferredSize(new Dimension(125, 70));
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        boton.revalidate();
        boton.repaint();
        panelSur.setLayout(new FlowLayout(FlowLayout.LEFT));
        panelSur.add(boton);
        panelSur.revalidate();
        panelSur.repaint();
    }
    /**
     * Este metodo es clave, es el encargado de que cada boton de modulo te lleve a la correspondiente ventana
     * todo esto utilizando el patron de diseño de FactoryMethod
     * @param boton
     * @param ventana
     * @param tipo 
     */
    private void configuracionBotonModulo(JButton boton, String ventana, TipoVentana tipo) {
        boton.setPreferredSize(new Dimension(200, 100));
        VentanaFactory fabrica = new VentanaFactory();
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navegacion.registrarVentana(ventana, fabrica.crearVentana(tipo));
                navegacion.abrirVentana(ventana);
                navegacion.cerrarVentana("Menu Administrador");
            }
        });
    }
}
