/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import BOs.ProductoBO;
import Control.ControlDeNavegacion;
import Control.IControl;
import Enums.Tipo;
import interfaces.IProductoBO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author rodri
 */
public class RegistroProducto extends VentanaBase {

    private IControl navegacion;
    private IProductoBO instanceBO;

    /**
     * Creates new form RegistroIngrediente
     */
    public RegistroProducto(IControl control) {
        super(control, "Registro Producto");
        navegacion = ControlDeNavegacion.getInstance();
        instanceBO = ProductoBO.getInstance();
        generarRegistroProducto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        btnRegreso = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNombre.setText("jLabel1");

        jTextFieldNombre.setText("jTextField1");

        jLabelTipo.setText("jLabel2");

        jLabelPrecio.setText("jLabel3");

        jTextFieldPrecio.setText("jTextField3");

        btnRegreso.setText("jButton1");

        btnAñadir.setText("jButton1");

        btnIngredientes.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnRegreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngredientes))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jLabelTipo)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnAñadir)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTipo)
                .addGap(52, 52, 52)
                .addComponent(jLabelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegreso)
                    .addComponent(btnIngredientes)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        navegacion.registrarVentana("Menu Productos", new MenuProductos(control));
        navegacion.abrirVentana("Menu Productos");
        navegacion.cerrarVentana("Registro Producto");
    }
    
    private void botonIngredientesMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        navegacion.registrarVentana("Menu Ingredientes", new MenuIngredientes(control));
        navegacion.abrirVentana("Menu Ingredientes");
        navegacion.cerrarVentana("Registro Producto");
    }
    
    private void botonAñadirMouseClicked(MouseEvent evt) {
        try {
            instanceBO.registrarProducto(jTextFieldNombre.getText(), jTextFieldPrecio.getText(), (Tipo) jComboBoxTipo.getSelectedItem());
            
            JOptionPane.showMessageDialog(null, "Ingrediente agregado exitosamente", "Ingrediente", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JComboBox<Tipo> jComboBoxTipo;
    /**
     * Metodo para generar la ventana del registro de ingredientes
     */
    private void generarRegistroProducto() {
        JPanel panelCentral = new JPanel();
        panelCentral.setLayout(new GridLayout(0, 1, 20, 20));
        panelCentral.setPreferredSize(new Dimension(300, 200)); // Ajusta el ancho del panel

        btnRegreso = new JButton("REGRESAR");
        btnIngredientes = new JButton("INGREDIENTES");
        generarBotonesDeAbajo(btnRegreso,btnIngredientes);
        
        
        
        btnAñadir = new JButton("AÑADIR");
        generarBotonAñadir(btnAñadir);

        jLabelNombre = new JLabel("Nombre:");
        jTextFieldNombre = new JTextField();
        jLabelTipo = new JLabel("Tipo:");
        jComboBoxTipo = new JComboBox<>(Tipo.values());
        jLabelPrecio = new JLabel("Precio:");
        jTextFieldPrecio = new JTextField();

        panelCentral.add(generacionPanel(jLabelNombre, jTextFieldNombre));
        panelCentral.add(generacionPanel2(jLabelTipo, jComboBoxTipo));
        panelCentral.add(generacionPanel(jLabelPrecio, jTextFieldPrecio));
        panelCentral.add(btnAñadir);
        
        generarPanelContenedor(panelCentral);

        revalidate();
        repaint();
    }
    /**
     * Este metodo genera un panel que es donde se unen los label y los textField
     * @param label
     * @param textField
     * @return 
     */
    private JPanel generacionPanel(JLabel label, JTextField textField) {
        JPanel panel = new JPanel();
        Font fuente = new Font("Arial", Font.BOLD, 18);
        label.setFont(fuente);
        label.setHorizontalAlignment(SwingConstants.LEFT);
        textField.setFont(fuente);
        textField.setPreferredSize(new Dimension(100, 25));
        panel.setLayout(new GridLayout(0, 1, 5, 5));
        panel.setMaximumSize(new Dimension(100, 500));
        panel.add(label);
        panel.add(textField);
        return panel;
    }
    /**
     * Este metodo genera un panel que es donde se unen los label y los comboBox
     * @param label
     * @param textField
     * @return 
     */
    private JPanel generacionPanel2(JLabel label, JComboBox comboBox) {
        JPanel panel = new JPanel();
        Font fuente = new Font("Arial", Font.BOLD, 18);
        label.setFont(fuente);
        label.setHorizontalAlignment(SwingConstants.LEFT);
        comboBox.setFont(fuente);
        comboBox.setPreferredSize(new Dimension(100, 25));
        panel.setLayout(new GridLayout(0, 1, 5, 5));
        panel.setMaximumSize(new Dimension(100, 500));
        panel.add(label);
        panel.add(comboBox);
        return panel;
    }
    /**
     * Metodo necesario para la generacion del boton de regreso e ingredientes
     * @param boton 
     */
    private void generarBotonesDeAbajo(JButton regreso, JButton ingredientes) {
        JPanel panelSur = (JPanel) this.getContentPane().getComponent(0);
        regreso.setPreferredSize(new Dimension(125, 70));
        ingredientes.setPreferredSize(new Dimension(125, 70));
        regreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        ingredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngredientesMouseClicked(evt);
            }
        });
        regreso.revalidate();
        regreso.repaint();
        ingredientes.revalidate();
        ingredientes.repaint();
        panelSur.setLayout(new BorderLayout());
        panelSur.add(regreso, BorderLayout.WEST);
        panelSur.add(ingredientes, BorderLayout.EAST);
        panelSur.revalidate();
        panelSur.repaint();
    }
    /**
     * Metodo para la generacion del boton para añadir los ingredientes
     * @param boton 
     */
    private void generarBotonAñadir(JButton boton) {
        boton.setPreferredSize(new Dimension(75, 40));
        boton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                botonAñadirMouseClicked(evt);
            }
        });
    }
    /**
     * Metodo para generar el panel que contrendar todos los componentes que iran en el centro
     * @param panelCentral 
     */
    private void generarPanelContenedor(JPanel panelCentral) {
        JPanel panelContenedor = new JPanel();
        panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.X_AXIS));
        
        // Panel de margen para centrar
        JPanel espacioIzquierdo = new JPanel();
        espacioIzquierdo.setPreferredSize(new Dimension(100, 1)); // Ajusta el ancho del margen

        JPanel espacioDerecho = new JPanel();
        espacioDerecho.setPreferredSize(new Dimension(100, 1)); // Ajusta el ancho del margen
        
        panelContenedor.add(espacioIzquierdo);
        panelContenedor.add(panelCentral);
        panelContenedor.add(espacioDerecho);
        
        add(panelContenedor, BorderLayout.CENTER);
    }
}
