/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import BOs.ClienteFrecuenteBO;
import Control.ControlDeNavegacion;
import Control.IControl;
import Exceptions.ClienteFrecuenteBOException;
import interfaces.IClienteFrecuenteBO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Daniel Miribe
 */
public class RegistroClientesFrecuentes extends VentanaBase {

    private Control.ControlDeNavegacion navegacion;
    private IClienteFrecuenteBO instanceBO;

    /**
     * Creates new form RegistroClientesFrecuentes
     */
    public RegistroClientesFrecuentes(IControl control) {
        super(control, "Registro Cliente Frecuente");
        navegacion = ControlDeNavegacion.getInstance();
        instanceBO = ClienteFrecuenteBO.getInstanceBO();
        generarRegistroClienteFrecuente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        jLabelApellidoPaterno = new javax.swing.JLabel();
        jTextFieldApellidoPaterno = new javax.swing.JTextField();
        jLabelApellidoMaterno = new javax.swing.JLabel();
        jTextFieldApellidoMaterno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNombre.setText("jLabel1");

        jTextFieldNombre.setText("jTextField1");

        jLabelTelefono.setText("jLabel2");

        jTextFieldTelefono.setText("jTextField2");

        jLabelCorreo.setText("jLabel3");

        jTextFieldCorreo.setText("jTextField3");

        btnRegistrar.setText("jButton1");

        btnRegreso.setText("jButton2");

        jLabelApellidoPaterno.setText("jLabel1");

        jTextFieldApellidoPaterno.setText("jTextField1");

        jLabelApellidoMaterno.setText("jLabel1");

        jTextFieldApellidoMaterno.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegreso)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidoMaterno)
                    .addComponent(jTextFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidoPaterno)
                    .addComponent(btnRegistrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCorreo)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefono))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelApellidoPaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelApellidoMaterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegreso)
                    .addComponent(btnRegistrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        navegacion.registrarVentana("Menu de Clientes Frecuentes", new MenuClientesFrecuentes(control));
        navegacion.abrirVentana("Menu de Clientes Frecuentes");
        navegacion.cerrarVentana("Registro Cliente Frecuente");
    }

    private void botonAñadirMouseClicked(MouseEvent evt) {
        try {
            String nombre = jTextFieldNombre.getText().trim();
            String apellidoPaterno = jTextFieldApellidoPaterno.getText().trim();
            String apellidoMaterno = jTextFieldApellidoMaterno.getText().trim();

            StringBuilder nombreCompletoBuilder = new StringBuilder();

            if (!nombre.isEmpty()) {
                nombreCompletoBuilder.append(nombre);
            }

            if (!apellidoPaterno.isEmpty()) {
                nombreCompletoBuilder.append(" ").append(apellidoPaterno);
            }

            if (!apellidoMaterno.isEmpty()) {
                nombreCompletoBuilder.append(" ").append(apellidoMaterno);
            }

            String nombreCompleto = nombreCompletoBuilder.toString().trim();
            
            instanceBO.registrarClienteFrecuente(nombreCompleto, jTextFieldTelefono.getText(), jTextFieldCorreo.getText());

            JOptionPane.showMessageDialog(null, "Cliente agregado exitosamente", "Cliente Frecuente", JOptionPane.INFORMATION_MESSAGE);
        } catch (ClienteFrecuenteBOException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JLabel jLabelApellidoMaterno;
    private javax.swing.JLabel jLabelApellidoPaterno;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JTextField jTextFieldApellidoMaterno;
    private javax.swing.JTextField jTextFieldApellidoPaterno;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
  
    /**
     * Metodo para generar la ventana del registro de ingredientes
     */
    private void generarRegistroClienteFrecuente() {
        JPanel panelCentral = new JPanel();
        panelCentral.setLayout(new GridLayout(0, 1, 20, 20));
        panelCentral.setPreferredSize(new Dimension(300, 200));

        btnRegreso = new JButton("REGRESAR");
        generarBotonRegreso(btnRegreso);

        btnRegistrar = new JButton("REGISTRAR");
        generarBotonRegistrar(btnRegistrar);

        jLabelNombre = new JLabel("Nombre:");
        jTextFieldNombre = new JTextField();
        jLabelApellidoPaterno = new JLabel("Apellido Paterno:");
        jTextFieldApellidoPaterno = new JTextField();
        jLabelApellidoMaterno = new JLabel("Apellido Materno:");
        jTextFieldApellidoMaterno = new JTextField();
        jLabelTelefono = new JLabel("Numero de telefono:");
        jTextFieldTelefono = new JTextField();
        jLabelCorreo = new JLabel("Correo electronico:");
        jTextFieldCorreo = new JTextField();

        panelCentral.add(generacionPanel(jLabelNombre, jTextFieldNombre));
        panelCentral.add(generacionPanel(jLabelApellidoPaterno, jTextFieldApellidoPaterno));
        panelCentral.add(generacionPanel(jLabelApellidoMaterno, jTextFieldApellidoMaterno));
        panelCentral.add(generacionPanel(jLabelTelefono, jTextFieldTelefono));
        panelCentral.add(generacionPanel(jLabelCorreo, jTextFieldCorreo));
        panelCentral.add(btnRegistrar);

        generarPanelContenedor(panelCentral);

        revalidate();
        repaint();
    }

    /**
     * Este metodo genera un panel que es donde se unen los label y los
     * textField
     *
     * @param label
     * @param textField
     * @return
     */
    private JPanel generacionPanel(JLabel label, JTextField textField) {
        JPanel panel = new JPanel();
        Font fuente = new Font("Arial", Font.BOLD, 18);
        label.setFont(fuente);
        label.setHorizontalAlignment(SwingConstants.LEFT);
        textField.setFont(fuente);
        textField.setPreferredSize(new Dimension(100, 25));
        panel.setLayout(new GridLayout(0, 1, 5, 5));
        panel.setMaximumSize(new Dimension(100, 500));
        panel.add(label);
        panel.add(textField);
        return panel;
    }

    /**
     * Metodo necesario para la generacion del boton de regreso
     *
     * @param boton
     */
    private void generarBotonRegreso(JButton boton) {
        JPanel panelSur = (JPanel) this.getContentPane().getComponent(0);
        boton.setPreferredSize(new Dimension(125, 70));
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        boton.revalidate();
        boton.repaint();
        panelSur.setLayout(new FlowLayout(FlowLayout.LEFT));
        panelSur.add(boton);
        panelSur.revalidate();
        panelSur.repaint();
    }

    /**
     * Metodo para la generacion del boton para registar clientes
     *
     * @param boton
     */
    private void generarBotonRegistrar(JButton boton) {
        boton.setPreferredSize(new Dimension(75, 40));
        boton.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                botonAñadirMouseClicked(evt);
            }
        });
    }

    /**
     * Metodo para generar el panel el cual contrenda todos los componentes que
     * iran en el centro
     *
     * @param panelCentral
     */
    private void generarPanelContenedor(JPanel panelCentral) {
        JPanel panelContenedor = new JPanel();
        panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.X_AXIS));

        // Panel de margen para centrar
        JPanel espacioIzquierdo = new JPanel();
        espacioIzquierdo.setPreferredSize(new Dimension(100, 1)); // Ajusta el ancho del margen

        JPanel espacioDerecho = new JPanel();
        espacioDerecho.setPreferredSize(new Dimension(100, 1)); // Ajusta el ancho del margen

        panelContenedor.add(espacioIzquierdo);
        panelContenedor.add(panelCentral);
        panelContenedor.add(espacioDerecho);

        add(panelContenedor, BorderLayout.CENTER);
    }
}
