/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Control.IControl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/**
 *
 * @author Ramon Valencia
 */
public abstract class VentanaBase extends JFrame {
    protected IControl control;
    private JLabel tituloVentana;

    public VentanaBase(IControl control, String titulo) {
        super(titulo);
        this.setLayout(new BorderLayout());
        this.control = control;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setSize(800, 650);
        this.setLocationRelativeTo(null);
        
        configurarFrame(tituloVentana, titulo);
    }
    

    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo necesario para la configuracion base de todos los frames que heredaran de este metodo
     * @param tituloVentana
     * @param titulo 
     */
    private void configurarFrame(JLabel tituloVentana, String titulo) {
        JPanel panelNorte = new JPanel();
        JPanel panelSur = new JPanel();
        configuracionNorte(panelNorte);
        configuracionSur(panelSur);
        
        
        tituloVentana = new JLabel();
        configurarTitulo(tituloVentana, titulo);
        
        panelNorte.add(tituloVentana);
        
        this.add(panelSur, BorderLayout.SOUTH);
        this.add(panelNorte, BorderLayout.NORTH);
        
    }
    /**
     * Metodo necesario para configurar el titulo de los JFrame
     * @param tituloVentana
     * @param titulo 
     */
    private void configurarTitulo(JLabel tituloVentana, String titulo) {
        tituloVentana.setSize(new Dimension(125, 55));
        tituloVentana.setText(titulo);
        tituloVentana.setHorizontalAlignment(SwingConstants.CENTER);
        tituloVentana.setVerticalAlignment(SwingConstants.CENTER);
        tituloVentana.setFont(new Font("Regular", Font.BOLD, 32));
    }
    /**
     * Metodo que se encarga de configurar la parte superior de un JFrame
     * @param panelNorte 
     */
    private void configuracionNorte(JPanel panelNorte){
        Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK);
        panelNorte.setPreferredSize(new Dimension(650, 70));
        panelNorte.setBorder(border);
    }
    /**
     * Metodo que se encarga de configurar la parte inferior de un JFrame 
     * @param panelSur 
     */
    private void configuracionSur(JPanel panelSur) {
        Border border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.BLACK);
        panelSur.setPreferredSize(new Dimension(650, 70));
        panelSur.setBorder(border);
    }
}
